# Generated by Django 5.0.4 on 2024-05-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='genearated_content',
            new_name='generated_content',
        ),
    ]
